package de.msz.games.games.herorealms;

public enum HeroRealmsSpecialActionMode {
	
	DISCARD,
	OPPONENT_DISCARD_CARD,
	PREPARE_CHAMPION,
	STUN_TARGET_CHAMPION,
	PUT_CARD_DISCARD_PILE_TOP_DECK,
	PUT_CHAMPION_DISCARD_PILE_TOP_DECK,
	SACRIFICE,
	CLERIC_BLESS,
	PUT_CHAMPION_DISCARD_INTO_PLAY,
	RANGER_TRACK,
	ACQUIRE_OPPONENT_DISCARD,
	WIZARD_FIREBALL,
	;
}
