package de.msz.games.games.herorealms;

public enum HeroRealmsAbilityType {
	
	HEALTH,
	GOLD,
	COMBAT,
	HEALTH_EACH_CHAMPION,
	COMBAT_EACH_CHAMPION,
	COMBAT_EACH_OTHER_CHAMPION,
	COMBAT_EACH_OTHER_GUARD,
	COMBAT_EACH_OTHER_FACTION,
	DRAW_CARD,
	DRAW_DISCARD_CARD,
	OPPONENT_DISCARD_CARD,
	PREPARE_CHAMPION,
	STUN_TARGET_CHAMPION,
	NEXT_ACTION_TOP_DECK,
	NEXT_ACQUIRE_TOP_DECK,
	NEXT_ACQUIRE_HAND,
	PUT_CARD_DISCARD_PILE_TOP_DECK,
	PUT_CHAMPION_DISCARD_PILE_TOP_DECK,
	SACRIFICE_HAND_OR_DISCARD_PILE,
	SACRIFICE_HAND_OR_DISCARD_PILE_COMBAT,
	;
}
